[project]
name = "nedrexapp"
version = "0.1.0"
description = ""
authors = [{name = "James Skelton", email = "james.skelton@newcastle.ac.uk"}]

dependencies = [
    "fastapi == 0.70.0",
    "uvicorn == 0.15.0",
    "cachetools == 4.2.4",
    "bicon == 1.3.2",
    "click == 8.0.3",
    "neo4j == 4.3.7",
    "python-multipart == 0.0.5",
    "requests == 2.26.0",
    "filelock == 3.3.2",
    "redis == 3.5.3",
    "pottery == 1.4.7",
    "gseapy <= 0.10.7",
    "gunicorn == 20.1.0",
    "slowapi == 0.1.6",
    "toml == 0.10.2",
    "pymongo == 4.2.0",
    "loguru == 0.6.0",
    "rq == 1.11.0",
    "more-itertools == 8.14.0",
    "py2neo == 2021.2.3",
    "docker == 6.0.0",
]

[project.optional-dependencies]
dev = [
     "pytest == 5.2"
]

[tool.setuptools]
packages = ["nedrexapi"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
